#!/usr/bin/env python3
#############################################################################
# Filename    : DHT11v2.py
# Description :	read the temperature and humidity data of random # gen
# Author      : freenove
# modification: 2021/07/19
########################################################################
import random as rd 
import time
from flask import Flask, render_template, url_for 


app: Flask = Flask(__name__)
app = Flask(__name__)


DHTPin = 11     #define the pin of DHT11

def TemperatureVariables():
    TempData = [0]*100
    for i in range(100):
        TempData[i] = rd.randrange(70,85)
    #return render_template('page.html'), str(dataTemp)
    #return str(dataTemp) #, render_template('page.html'))
    return render_template('TempPage.html', data=TempData)    

@app.route('/')
def home():
    return 'TemperatureVariables'
        
if __name__ == '__main__':

    app.run(debug=True, host='0.0.0.0')
